// Pool von über 300 deutschen Lebensweisheiten
// Moderne, ermutigende und lebensnahe Sprüche

const QUOTES = [
    // Mut & Selbstvertrauen (1-40)
    "Jeder neue Tag ist eine Chance, mutiger zu sein als gestern.",
    "Deine Stärke liegt nicht darin, nie zu fallen, sondern immer wieder aufzustehen.",
    "Vertraue dir selbst. Du weißt mehr, als du denkst.",
    "Mut bedeutet nicht, keine Angst zu haben, sondern trotz der Angst zu handeln.",
    "Du bist stärker, als deine Zweifel dir einreden wollen.",
    "Kleine Schritte in die richtige Richtung sind immer noch Fortschritt.",
    "Deine Komfortzone ist ein schöner Ort, aber dort wächst nichts.",
    "Manchmal ist der erste Schritt der schwerste. Aber er lohnt sich.",
    "Du musst nicht perfekt sein, um wertvoll zu sein.",
    "Deine Geschichte ist einzigartig. Niemand kann sie so erzählen wie du.",
    "Fehler sind Beweise dafür, dass du es versuchst.",
    "Du darfst stolz auf dich sein, auch für die kleinen Dinge.",
    "Jeder Meister war einmal ein Anfänger.",
    "Deine Träume sind gültig, egal wie unrealistisch sie anderen erscheinen.",
    "Sei mutig genug, unperfekt anzufangen.",
    "Deine Meinung über dich selbst zählt am meisten.",
    "Du bist nicht hier, um wie alle anderen zu sein.",
    "Manchmal ist das Mutigste, was du tun kannst, um Hilfe zu bitten.",
    "Vergleiche dich nicht mit anderen. Vergleiche dich mit dem, der du gestern warst.",
    "Du hast schon so viel geschafft. Erinnere dich daran.",
    "Deine Zweifel dürfen da sein, aber sie müssen nicht das Steuer übernehmen.",
    "Sei freundlich zu dir selbst. Du gibst dein Bestes.",
    "Niemand kennt deinen Weg besser als du selbst.",
    "Du darfst Fehler machen. Sie gehören zum Lernen dazu.",
    "Dein Wert hängt nicht von deiner Leistung ab.",
    "Heute ist ein guter Tag, um etwas Neues zu wagen.",
    "Du bist mutiger, als du glaubst, und stärker, als du weißt.",
    "Manchmal reicht es, einfach weiterzumachen.",
    "Deine Stimme verdient es, gehört zu werden.",
    "Warte nicht auf den perfekten Moment. Schaffe ihn.",
    "Du musst nicht alles alleine schaffen.",
    "Deine Verletzlichkeit ist keine Schwäche, sondern Stärke.",
    "Jeder Tag bietet die Chance für einen Neuanfang.",
    "Du darfst dir selbst erlauben, zu wachsen.",
    "Manchmal ist Nichtstun der mutigste Akt der Selbstfürsorge.",
    "Deine Unsicherheiten machen dich menschlich, nicht weniger wertvoll.",
    "Du bist genug. Genau so, wie du bist.",
    "Kleine Erfolge verdienen genauso viel Anerkennung wie große.",
    "Du darfst deine Meinung ändern. Das zeigt, dass du wächst.",
    "Vertraue dem Prozess, auch wenn du das Ziel noch nicht siehst.",

    // Achtsamkeit & Gegenwart (41-80)
    "Das Leben passiert jetzt. Nicht gestern, nicht morgen.",
    "Manchmal ist der beste Plan, einfach zu atmen und zu vertrauen.",
    "Die kleinen Momente sind es, die das große Ganze ausmachen.",
    "Heute ist das einzige Geschenk, das wirklich zählt.",
    "Nimm dir Zeit für die Dinge, die deine Seele nähren.",
    "Nicht jeder Tag wird großartig sein. Und das ist okay.",
    "Manchmal ist das Wichtigste, einfach präsent zu sein.",
    "Achte auf das, was du in deinem Leben willkommen heißt.",
    "Deine Energie ist kostbar. Investiere sie weise.",
    "Pause machen ist produktiv.",
    "Es ist okay, nicht okay zu sein.",
    "Hör auf deinen Körper. Er weiß, was er braucht.",
    "Manchmal braucht es Stille, um die eigene Stimme zu hören.",
    "Die Antwort liegt oft nicht im Außen, sondern im Innen.",
    "Du darfst langsamer machen. Das Leben ist kein Wettrennen.",
    "Manchmal ist weniger wirklich mehr.",
    "Jeder Atemzug ist eine Gelegenheit, neu zu beginnen.",
    "Die besten Dinge im Leben kann man nicht kaufen.",
    "Sei dort, wo deine Füße sind.",
    "Deine Ruhe ist genauso wichtig wie deine Produktivität.",
    "Manchmal ist das größte Abenteuer, bei dir selbst anzukommen.",
    "Die Gegenwart ist das einzige, was du wirklich beeinflussen kannst.",
    "Nimm dir Zeit für das, was dich lebendig fühlen lässt.",
    "Dankbarkeit verwandelt das, was wir haben, in genug.",
    "Manchmal bedeutet Stärke, nachzugeben statt durchzuhalten.",
    "Die Stille hält oft die besten Antworten bereit.",
    "Du musst nicht jeden Tag gleich produktiv sein.",
    "Höre mehr zu – dir selbst und anderen.",
    "Manchmal ist das Wertvollste, was du geben kannst, deine Aufmerksamkeit.",
    "Das Hier und Jetzt ist der einzige Moment, der wirklich existiert.",
    "Sei geduldig mit dir. Heilung braucht Zeit.",
    "Nicht alles, was wichtig ist, ist auch dringend.",
    "Manchmal reicht es, einfach zu sein, statt zu tun.",
    "Deine Grenzen zu kennen ist eine Form von Weisheit.",
    "Nimm dir Zeit, die Schönheit im Alltäglichen zu sehen.",
    "Manchmal ist das Loslassen die größte Befreiung.",
    "Dein innerer Frieden ist wichtiger als äußere Anerkennung.",
    "Atme tief. Es wird alles gut.",
    "Manchmal ist die beste Entscheidung, keine Entscheidung zu treffen.",
    "Die Reise ist oft wichtiger als das Ziel.",

    // Beziehungen & Miteinander (81-120)
    "Die Menschen, die dich lieben, werden auf dich warten.",
    "Echte Verbindungen entstehen in der Verletzlichkeit.",
    "Sei die Person, die du in deinem Leben gebraucht hättest.",
    "Freundlichkeit ist nie verschwendet.",
    "Du musst nicht jeden Menschen in deinem Leben behalten.",
    "Grenzen zu setzen ist ein Akt der Selbstliebe.",
    "Die besten Beziehungen sind die, in denen du du selbst sein kannst.",
    "Manchmal ist Schweigen die lauteste Form der Kommunikation.",
    "Zuhören ist eine Form der Liebe.",
    "Du verdienst Menschen, die für dich bleiben.",
    "Nicht jede Beziehung ist fürs Leben. Manche sind fürs Lernen.",
    "Sei großzügig mit deiner Wertschätzung.",
    "Manchmal ist das größte Geschenk, einfach da zu sein.",
    "Liebe beginnt damit, sich selbst zu akzeptieren.",
    "Die richtigen Menschen werden deine Bemühungen sehen.",
    "Du musst dich nicht kleiner machen, damit andere größer wirken.",
    "Ehrlichkeit ist das Fundament jeder echten Verbindung.",
    "Manchmal bedeutet Liebe, loszulassen.",
    "Umgib dich mit Menschen, die dich wachsen lassen.",
    "Du verdienst Liebe, die sich leicht anfühlt.",
    "Sei freundlich. Jeder kämpft einen Kampf, von dem du nichts weißt.",
    "Die besten Gespräche entstehen, wenn wir wirklich zuhören.",
    "Deine Energie zieht die richtigen Menschen an.",
    "Manchmal ist Vergebung ein Geschenk an dich selbst.",
    "Qualität geht vor Quantität – auch bei Freundschaften.",
    "Du bist nicht verantwortlich für die Gefühle anderer.",
    "Echte Freunde feiern deine Erfolge mit dir.",
    "Manchmal ist das Wichtigste, einfach zu sagen: Ich bin für dich da.",
    "Liebe ist keine Transaktion. Sie ist ein Geschenk.",
    "Die Menschen, die bleiben, sind die, die zählen.",
    "Respekt ist die Grundlage jeder gesunden Beziehung.",
    "Du darfst Nein sagen, auch zu Menschen, die du liebst.",
    "Manchmal ist das beste Geschenk, jemandem wirklich zu begegnen.",
    "Beziehungen brauchen Pflege, wie ein Garten.",
    "Du verdienst Menschen, die dich wählen, nicht nur akzeptieren.",
    "Sei authentisch. Die richtigen Menschen werden bleiben.",
    "Manchmal ist die größte Liebe, jemandem Raum zu geben.",
    "Dankbarkeit vertieft jede Beziehung.",
    "Du musst nicht perfekt sein, um geliebt zu werden.",
    "Echte Verbindungen überstehen auch schwierige Zeiten.",

    // Veränderung & Wachstum (121-160)
    "Veränderung ist der einzige Beweis dafür, dass du lebst.",
    "Wachstum geschieht oft außerhalb deiner Komfortzone.",
    "Nicht alle Veränderungen fühlen sich sofort gut an.",
    "Du darfst dich neu erfinden, so oft du willst.",
    "Manchmal musst du alte Versionen von dir loslassen.",
    "Jeder Rückschlag ist eine Einladung, einen neuen Weg zu finden.",
    "Veränderung beginnt in dem Moment, in dem du dich entscheidest.",
    "Du bist nicht hier, um zu stagnieren.",
    "Manchmal ist das Ende eines Kapitels der Beginn des besten.",
    "Wachstum ist selten linear. Und das ist völlig okay.",
    "Du darfst deine Pläne ändern. Das Leben tut es auch.",
    "Manchmal bedeutet Fortschritt, zwei Schritte zurück zu gehen.",
    "Jede Erfahrung formt dich, auch die schwierigen.",
    "Du bist nicht dieselbe Person, die du vor einem Jahr warst. Und das ist gut so.",
    "Veränderung ist unbequem, aber notwendig.",
    "Manchmal musst du loslassen, um weiterzukommen.",
    "Dein Wachstum ist wichtiger als die Meinung anderer.",
    "Nicht jeder wird deine Veränderung verstehen. Du musst sie trotzdem leben.",
    "Manchmal bedeutet Heilung, sich von alten Mustern zu verabschieden.",
    "Du darfst werden, wer du wirklich bist.",
    "Jeder Tag ist eine neue Gelegenheit, zu wachsen.",
    "Veränderung braucht Zeit. Sei geduldig mit dir.",
    "Manchmal ist der größte Mut, sich selbst treu zu bleiben.",
    "Du bist in ständiger Entwicklung. Genieße die Reise.",
    "Nicht alle Türen, die sich schließen, waren die richtigen.",
    "Manchmal ist das Beste, was dir passieren kann, dass Pläne scheitern.",
    "Deine Vergangenheit definiert nicht deine Zukunft.",
    "Du darfst aus deinen Fehlern lernen, ohne dich dafür zu verurteilen.",
    "Manchmal ist der größte Fortschritt unsichtbar.",
    "Wachstum bedeutet nicht, dass du früher falsch lagst.",
    "Du darfst dich weiterentwickeln, auch wenn andere dich festhalten wollen.",
    "Manchmal ist Veränderung das beste Geschenk, das du dir machen kannst.",
    "Jede Version von dir war notwendig für die, die du heute bist.",
    "Du bist nicht zu alt, um neu zu beginnen.",
    "Manchmal bedeutet Wachstum, sich von toxischen Situationen zu lösen.",
    "Veränderung ist ein Zeichen von Leben, nicht von Scheitern.",
    "Du darfst dir Zeit nehmen, um herauszufinden, wer du sein willst.",
    "Manchmal ist das Loslassen alter Träume der Beginn besserer.",
    "Dein Wachstum muss niemandem außer dir Sinn ergeben.",
    "Jeder Neuanfang ist eine Chance, es anders zu machen.",

    // Resilienz & Durchhaltevermögen (161-200)
    "Auch der längste Weg beginnt mit einem ersten Schritt.",
    "Du hast schon Schwieriges gemeistert. Du wirst auch das hier schaffen.",
    "Manchmal ist Durchhalten die mutigste Entscheidung.",
    "Nicht aufgeben bedeutet nicht, sich nicht auszuruhen.",
    "Deine Kraft liegt darin, trotz allem weiterzumachen.",
    "Schwierige Zeiten formen starke Menschen.",
    "Manchmal musst du durch den Sturm, um den Regenbogen zu sehen.",
    "Du bist widerstandsfähiger, als du denkst.",
    "Jeder Tag, den du durchhältst, ist ein Sieg.",
    "Manchmal ist die größte Stärke, um Hilfe zu bitten.",
    "Du musst nicht jeden Tag stark sein.",
    "Rückschläge sind keine Niederlagen, sondern Umwege.",
    "Manchmal braucht es die dunkelsten Nächte für die hellsten Sterne.",
    "Deine Geschichte ist noch nicht zu Ende.",
    "Auch Berge werden Schritt für Schritt bestiegen.",
    "Manchmal ist das Weitermachen wichtiger als das Wie.",
    "Du darfst stolz auf dich sein, auch wenn niemand sonst es sieht.",
    "Schwierigkeiten sind temporär. Deine Stärke ist permanent.",
    "Manchmal musst du dich selbst tragen, bis du wieder gehen kannst.",
    "Jeder Morgen ist ein Beweis deiner Stärke.",
    "Du hast schon 100% deiner schlechtesten Tage überlebt.",
    "Manchmal ist das Geheimnis, einfach noch einen Tag durchzuhalten.",
    "Deine Narben sind Beweise deiner Heilung.",
    "Nicht jeder Tag wird einfach sein. Aber er wird vorbeigehen.",
    "Manchmal ist der einzige Weg durch etwas hindurch.",
    "Du bist stärker, als deine Herausforderungen es sind.",
    "Auch in schweren Zeiten gibt es kleine Lichtblicke.",
    "Manchmal bedeutet Stärke, weiterzumachen, wenn niemand zuschaut.",
    "Deine Ausdauer wird sich auszahlen.",
    "Schwierige Phasen sind oft die Vorboten von Wachstum.",
    "Manchmal musst du erst durch das Tal, um den Gipfel zu erreichen.",
    "Du darfst müde sein und trotzdem weitermachen.",
    "Jeder Kampf, den du kämpfst, macht dich stärker.",
    "Manchmal ist Hoffnung das Einzige, was du brauchst.",
    "Deine Kraft liegt darin, immer wieder aufzustehen.",
    "Auch kleine Fortschritte sind Fortschritte.",
    "Manchmal reicht es, einfach zu überleben, um zu gewinnen.",
    "Du bist nicht allein, auch wenn es sich so anfühlt.",
    "Jeder Sturm geht vorbei. Auch deiner.",
    "Manchmal ist das größte Wunder, dass du immer noch hier bist.",

    // Kreativität & Selbstausdruck (201-240)
    "Deine Kreativität ist ein Geschenk an die Welt.",
    "Perfektion ist der Feind der Kreativität.",
    "Manchmal ist das Schaffen wichtiger als das Ergebnis.",
    "Deine Kunst muss niemandem außer dir gefallen.",
    "Jeder Mensch ist auf seine Weise kreativ.",
    "Manchmal ist das Unperfekte das Schönste.",
    "Du darfst experimentieren, ohne ein Meisterwerk zu schaffen.",
    "Kreativität braucht Mut zur Unvollkommenheit.",
    "Manchmal ist der Prozess wichtiger als das Produkt.",
    "Deine Perspektive ist einzigartig und wertvoll.",
    "Nicht jede Idee muss sofort perfekt sein.",
    "Manchmal beginnt die beste Kunst mit einem Fehler.",
    "Du darfst dich kreativ ausdrücken, ohne dich zu erklären.",
    "Inspiration kommt oft in den unerwartetsten Momenten.",
    "Manchmal ist das Wichtigste, einfach anzufangen.",
    "Deine Stimme verdient es, ausgedrückt zu werden.",
    "Kreativität ist kein Talent, sondern eine Entscheidung.",
    "Manchmal ist das beste Kunstwerk das, das aus dem Herzen kommt.",
    "Du musst nicht gut sein, um kreativ zu sein.",
    "Jede Idee verdient es, gehört zu werden.",
    "Manchmal ist das Unperfekte authentischer.",
    "Deine Kreativität ist eine Form der Selbstfürsorge.",
    "Nicht jedes Projekt muss fertig werden.",
    "Manchmal ist das Schaffen selbst die Belohnung.",
    "Du darfst spielerisch und experimentell sein.",
    "Kreativität braucht keine Rechtfertigung.",
    "Manchmal ist der erste Entwurf der ehrlichste.",
    "Deine Art zu sehen ist deine Superkraft.",
    "Nicht jede Idee muss neu sein, um wertvoll zu sein.",
    "Manchmal ist das Schaffen ein Akt der Rebellion.",
    "Du darfst deine Kunst für dich selbst machen.",
    "Kreativität ist der Mut, du selbst zu sein.",
    "Manchmal ist das Wichtigste, deiner Neugier zu folgen.",
    "Deine Kreativität ist grenzenlos.",
    "Nicht jeder wird verstehen, was du erschaffst. Das ist okay.",
    "Manchmal ist das Schaffen die beste Therapie.",
    "Du darfst wild und ungezähmt kreativ sein.",
    "Jeder kreative Akt ist ein Akt der Freiheit.",
    "Manchmal ist das Unperfekte das Menschlichste.",
    "Deine Kreativität ist ein Teil dessen, wer du bist.",

    // Lebensfreude & Dankbarkeit (241-280)
    "Freude findet sich oft in den kleinen Dingen.",
    "Lachen ist eine Form von Medizin.",
    "Manchmal ist das beste Rezept für einen guten Tag, zu lächeln.",
    "Dankbarkeit verwandelt Alltägliches in Besonderes.",
    "Nimm dir Zeit für das, was dich glücklich macht.",
    "Manchmal ist das größte Glück, einfach zu sein.",
    "Du verdienst Freude in deinem Leben.",
    "Nicht jeder Tag wird perfekt sein, aber jeder Tag hat schöne Momente.",
    "Manchmal ist das Wertvollste, gemeinsam zu lachen.",
    "Dankbarkeit ist der Schlüssel zu mehr Zufriedenheit.",
    "Nimm dir Zeit für Dinge, die keine Produktivität erfordern.",
    "Manchmal ist Freude eine bewusste Entscheidung.",
    "Du darfst das Leben feiern, auch ohne Grund.",
    "Die schönsten Momente sind oft die ungeplanten.",
    "Manchmal ist das Glück näher, als du denkst.",
    "Dankbarkeit macht aus Wenig viel.",
    "Nimm dir Zeit, die Schönheit um dich herum zu sehen.",
    "Manchmal ist das größte Abenteuer, das Leben zu genießen.",
    "Du verdienst es, dich lebendig zu fühlen.",
    "Freude ist ansteckend. Teile sie.",
    "Manchmal ist das beste Geschenk, den Moment zu genießen.",
    "Dankbarkeit verändert die Art, wie wir die Welt sehen.",
    "Nimm dir Zeit für Menschen, die dich zum Lachen bringen.",
    "Manchmal ist Glück einfach nur Zufriedenheit.",
    "Du darfst das Leben leicht nehmen.",
    "Die kleinen Freuden sind es, die das Leben reich machen.",
    "Manchmal ist der beste Plan, keinen Plan zu haben.",
    "Dankbarkeit ist die Erinnerung des Herzens.",
    "Nimm dir Zeit zum Spielen, auch als Erwachsener.",
    "Manchmal ist Freude die beste Form des Protests.",
    "Du verdienst Momente, in denen du nichts tun musst.",
    "Lachen verbindet mehr als Worte.",
    "Manchmal ist das Schönste, einfach zu staunen.",
    "Dankbarkeit öffnet die Tür zu mehr Fülle.",
    "Nimm dir Zeit für Sonnenuntergänge und Sternenhimmel.",
    "Manchmal ist Glück eine Frage der Perspektive.",
    "Du darfst das Leben feiern, so wie es ist.",
    "Freude braucht keine großen Anlässe.",
    "Manchmal ist das Wertvollste, einfach präsent zu sein.",
    "Dankbarkeit ist ein Geschenk, das du dir selbst machst.",

    // Weisheit & Lebensphilosophie (281-320)
    "Das Leben ist zu kurz für Dinge, die dir keine Energie geben.",
    "Manchmal ist weniger wirklich mehr.",
    "Weisheit liegt darin, zu wissen, was wirklich wichtig ist.",
    "Du musst nicht alles verstehen, um es zu akzeptieren.",
    "Manchmal ist die beste Antwort, keine Antwort zu geben.",
    "Leben ist das, was passiert, während du Pläne machst.",
    "Du darfst deine Prioritäten neu ordnen.",
    "Manchmal ist der Weg das Ziel.",
    "Nicht alles, was zählt, kann gezählt werden.",
    "Weisheit beginnt mit der Erkenntnis, wie viel du nicht weißt.",
    "Manchmal ist das Loslassen weiser als das Festhalten.",
    "Du musst nicht auf alles eine Antwort haben.",
    "Leben bedeutet, ständig zu lernen.",
    "Manchmal ist die beste Lektion die, die wir nicht gesucht haben.",
    "Nicht jede Frage braucht sofort eine Antwort.",
    "Weisheit ist, zu wissen, wann man sprechen und wann man schweigen soll.",
    "Manchmal ist das Beste, was du tun kannst, zu vertrauen.",
    "Du darfst deine Wahrheit leben, auch wenn sie anders ist.",
    "Leben ist eine Balance zwischen Festhalten und Loslassen.",
    "Manchmal ist die größte Weisheit, einfach zu sein.",
    "Nicht jeder Moment braucht eine Bedeutung.",
    "Weisheit liegt darin, aus Fehlern zu lernen, nicht sie zu vermeiden.",
    "Manchmal ist das Leben simpler, als wir denken.",
    "Du musst nicht alles kontrollieren.",
    "Leben ist das, was zwischen den Plänen passiert.",
    "Manchmal ist die beste Philosophie, im Moment zu sein.",
    "Nicht alles muss Sinn ergeben.",
    "Weisheit ist, zu akzeptieren, was ist.",
    "Manchmal ist das Wertvollste, was wir haben, Zeit.",
    "Du darfst deine Meinung ändern, wenn du Neues lernst.",
    "Leben bedeutet, immer wieder neu anzufangen.",
    "Manchmal ist die größte Weisheit, auf dein Herz zu hören.",
    "Nicht jede Entscheidung muss für immer sein.",
    "Weisheit ist, zu wissen, dass du genug bist.",
    "Manchmal ist das Leben chaotisch. Und das ist okay.",
    "Du musst nicht jeden Tag produktiv sein, um wertvoll zu sein.",
    "Leben ist eine Sammlung von Momenten, nicht von Dingen.",
    "Manchmal ist die beste Entscheidung, keine zu treffen.",
    "Nicht alles braucht eine Erklärung.",
    "Weisheit ist, zu erkennen, was du ändern kannst und was nicht."
];

// Funktion zum Abrufen eines zufälligen Spruchs
function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * QUOTES.length);
    return QUOTES[randomIndex];
}

// Funktion zum Erstellen einer neuen Spruchzuordnung
function generateQuoteMapping(numberOfDays) {
    const availableQuotes = [...QUOTES];
    const mapping = [];

    for (let i = 0; i < numberOfDays; i++) {
        if (availableQuotes.length === 0) {
            // Falls wir mehr Tage als Sprüche haben, befülle das Array neu
            availableQuotes.push(...QUOTES);
        }

        // Zufälligen Spruch auswählen
        const randomIndex = Math.floor(Math.random() * availableQuotes.length);
        mapping.push(availableQuotes[randomIndex]);

        // Ausgewählten Spruch entfernen, um Wiederholungen zu vermeiden
        availableQuotes.splice(randomIndex, 1);
    }

    return mapping;
}

// Export für Verwendung in anderen Dateien
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { QUOTES, getRandomQuote, generateQuoteMapping };
}
